<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="diff_drive_controller" params="wheel_separation wheel_radius wheel_torque">
    <gazebo>
      <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
        <updateRate>100.0</updateRate>
        <robotNamespace></robotNamespace>
        <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>
        <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>
        <leftRearJoint>rear_left_wheel_joint</leftRearJoint>
        <rightRearJoint>rear_right_wheel_joint</rightRearJoint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
        <robotBaseFrame>base_link</robotBaseFrame>
        <torque>{wheel_torque}</torque>
        <topicName>cmd_vel</topicName>
        <broadcastTF>false</broadcastTF>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>